// generated by stringer -type=Token token.go; DO NOT EDIT

package logstash

import "fmt"

const _Token_name = "TokenIllegalTokenEOFTokenUnexpectedEOFTokenWhitespaceTokenIdentifierTokenAssignmentTokenLCurlyBraceTokenLBracketTokenLParenTokenRParenTokenRCurlyBraceTokenRBracketTokenStringTokenNumberTokenIfTokenElseTokenCommentTokenCommaTokenBoolTokenEqRegexTokenNEqRegexTokenEqTokenNEqTokenLTTokenGTTokenLTETokenGTETokenAndTokenOrTokenInTokenNotInTokenNandTokenXorTokenNotTokenNegateTokenRegex"

var _Token_index = [...]uint16{0, 12, 20, 38, 53, 68, 83, 99, 112, 123, 134, 150, 163, 174, 185, 192, 201, 213, 223, 232, 244, 257, 264, 272, 279, 286, 294, 302, 310, 317, 324, 334, 343, 351, 359, 370, 380}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return fmt.Sprintf("Token(%d)", i)
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
